// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_dlco0yjmhXvqbFsEY4CdNK4eg4dli4',
    appId: '1:764954781636:web:804e9783175c88e92ee691',
    messagingSenderId: '764954781636',
    projectId: 'bronze-mirror',
    authDomain: 'bronze-mirror.firebaseapp.com',
    storageBucket: 'bronze-mirror.firebasestorage.app',
    measurementId: 'G-9JSNFQ46MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYgEms4tRyjATpAQpTaRvXqE92a9UNxEE',
    appId: '1:764954781636:android:ce45c9b812bd8ad02ee691',
    messagingSenderId: '764954781636',
    projectId: 'bronze-mirror',
    storageBucket: 'bronze-mirror.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb8DVHaYIJSw84NMzUYDef_ZJ09V_oZwA',
    appId: '1:764954781636:ios:483c2f9d51f606ef2ee691',
    messagingSenderId: '764954781636',
    projectId: 'bronze-mirror',
    storageBucket: 'bronze-mirror.firebasestorage.app',
    iosBundleId: 'com.example.bronzeMirror',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb8DVHaYIJSw84NMzUYDef_ZJ09V_oZwA',
    appId: '1:764954781636:ios:483c2f9d51f606ef2ee691',
    messagingSenderId: '764954781636',
    projectId: 'bronze-mirror',
    storageBucket: 'bronze-mirror.firebasestorage.app',
    iosBundleId: 'com.example.bronzeMirror',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBd_dlco0yjmhXvqbFsEY4CdNK4eg4dli4',
    appId: '1:764954781636:web:8b7604ba93ef6e4d2ee691',
    messagingSenderId: '764954781636',
    projectId: 'bronze-mirror',
    authDomain: 'bronze-mirror.firebaseapp.com',
    storageBucket: 'bronze-mirror.firebasestorage.app',
    measurementId: 'G-Y19GF00CNQ',
  );
}
